extension radius

@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object

// Create gateway resource if ingress property is set to true
resource gateway 'Applications.Core/gateways@2023-10-01-preview' = if (context.resource.properties.ingress) {
  name: 'gateway'
  properties: {
    application: context.application.id
    routes: [
      {
        path: '/'
        destination: 'http://${frontend.name}:${context.resource.properties.container.ports.web.containerPort}'
      }
    ]
  }
}

resource frontend 'Applications.Core/containers@2023-10-01-preview' = {
  name: 'frontend'
  properties: {
    application: context.application.id
    container: context.resource.properties.container
    connections: context.resource.properties.connections
  }
}
