# yaml-language-server: $schema=https://www.schemastore.org/dependabot-2.0.json
# See GitHub's documentation for more information on this file:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
---
version: 2

updates:
  - package-ecosystem: github-actions
    target-branch: edge
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
      include: scope
    ignore:
      - dependency-name: Azure/static-web-apps-deploy
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: devcontainers
    target-branch: edge
    directory: /
    schedule:
      interval: weekly
