apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-certificate
spec:
  commonName: YOUR_DOMAIN
  dnsNames:
  - YOUR_DOMAIN
  issuerRef:
    name: demo-issuer
    kind: ClusterIssuer
  secretName: demo-secret
