apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: demo-issuer
spec:
  acme:
    email: YOUR_EMAIL
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          azureDNS:
            clientID: CLIENT_ID
            clientSecretSecretRef:
              name: azuredns-config
              key: client-secret
            subscriptionID: SUBSCRIPTION_ID
            tenantID: TENANT_ID
            resourceGroupName: AZURE_DNS_RG
            hostedZoneName: YOUR_HOSTED_ZONE_NAME
            environment: AzurePublicCloud
