apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: demo-issuer
spec:
  acme:
    email: YOUR_EMAIL
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: contour
