apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctnr-sidecar
  labels:
    app: ctnr-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctnr-sidecar
  template:
    metadata:
      labels:
        app: ctnr-sidecar
    spec:
      containers:
        - name: ctnr-sidecar
          image: radiusdev.azurecr.io/magpie:latest