apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-yaml-app
  labels:
    app: base-yaml-app
  annotations:
    source: base-yaml-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base-yaml-app
  template:
    metadata:
      labels:
        app: base-yaml-app
    spec:
      containers:
        - name: log-collector
          image: ghcr.io/radius-project/fluent-bit:2.1.8