name: PR Checks

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, labeled, unlabeled]

jobs:
  check-do-not-merge-tag:
    name: Check for do-not-merge tag
    runs-on: ubuntu-latest
    steps:
      - name: Check for do-not-merge label
        run: |
          for label in ${{ github.event.pull_request.labels }}; do
            echo "Checking label: $label"
            if [[ "$label" == *"do-not-merge"* ]]; then
              echo "Error: PR contains do-not-merge label"
              exit 1
            fi
          done
