# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: PR Checks

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

jobs:
  check-do-not-merge-tag:
    name: Check for do-not-merge tag
    runs-on: ubuntu-latest
    steps:
      - name: Check for do-not-merge label
        uses: mheap/github-action-required-labels@8afbe8ae6ab7647d0c9f0cfa7c2f939650d22509 # v5.5.1
        with:
          labels: do-not-merge
          mode: exactly
          count: 0
