name: PR Checks

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, labeled, unlabeled]

jobs:
  check-do-not-merge-tag:
    name: Check for do-not-merge tag
    runs-on: ubuntu-latest
    steps:
      - name: Check for do-not-merge label
        run: |
          if grep -q "do-not-merge" ${{ github.event.pull_request.labels }}; then
            echo "Error: PR contains do-not-merge label"
            exit 1
          fi
