name: PR Checks

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, labeled, unlabeled]

jobs:
  check-do-not-merge-tag:
    name: Check for do-not-merge tag
    runs-on: ubuntu-latest
    steps:
      - name: Check for do-not-merge label
        if: contains(github.event.pull_request.labels.*.name, 'do-not-merge')
        run: |
            echo "Error: PR contains do-not-merge label"
            exit 1
      - name: Success
        run: |
            echo "Success: PR does not contain do-not-merge label"

