name: Radius Redirect

on:
  workflow_dispatch:
  push:
    branches:
      - edge
      - v*.*
    paths: 
      - 'redirect/**'
      - '.github/workflows/redirect.yml'
  pull_request:
    branches:
      - edge
      - v*.*
    paths: 
      - 'redirect/**'
      - '.github/workflows/redirect.yml'

jobs:
  deploy-website:
    name: Deploy Redirect Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Deploy staging site
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.SWA_REDIRECT_TOKEN }}
          action: "upload"
          app_location: "redirect/src"
          skip_api_build: true
          skip_app_build: true

  close_pr_site:
    name: Close PR Staging Site
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.SWA_REDIRECT_TOKEN }}
          action: "close"
