name: Spellcheck

on:
  workflow_dispatch:
  push:
    branches:
      - v*.*
      - edge
    paths:
      - 'docs/**'
      - '.github/workflows/spellcheck.yaml'
      - '.github/config/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - v*.*
    paths:
      - 'docs/**'
      - '.github/workflows/spellcheck.yaml'
      - '.github/config/**'

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout docs
      uses: actions/checkout@master
    - name: Spellcheck
      uses: rojopolis/spellcheck-github-actions@0.27.0
      with:
        config_path: .github/config/.pyspelling.yml
