# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# ------------------------------------------------------------

name: Validate Bicep Code
on:
  pull_request:
    branches:
      - edge
      - v*
jobs:
  build:
    name: Validate Bicep Code
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: az CLI login
      run: |
        az login --service-principal \
          --username ${{ secrets.AZURE_SP_TESTS_APPID }} \
          --password ${{ secrets.AZURE_SP_TESTS_PASSWORD }} \
          --tenant ${{ secrets.AZURE_SP_TESTS_TENANTID }}
    - name: Parse release version and set environment variables
      run: python ./.github/scripts/get_docs_version.py
    - name: Download rad-bicep
      run: |
        ./.github/scripts/curl-with-retries.sh https://get.radapp.dev/tools/bicep-extensibility/${{ env.DOCS_CHANNEL }}/linux-x64/rad-bicep --output rad-bicep
        chmod +x rad-bicep
        ./rad-bicep --version
    - name: Verify Bicep files
      run: python ./.github/scripts/validate-bicep.python
